# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rahul Gaba
email: rahulgaba16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A JavaScript Developer who loves to sing, ride, eat and play foosball.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rahulgaba.com" # the base hostname & protocol for your site
twitter_username: rahulgaba16
github_username:  rahulgaba16

# Build settings
markdown: kramdown
